### ISSUE TITLE
Suggestions for Application Name

### ISSUE THREAD

**Issue by ybuchi** [Linag94/dreamteam3#4]
Some suggestions: 

- HomeChef | Home Cook
- FoodHub | CookingHub | 'Something' Hub
- La cuisinette  (french for the little kitchen)

(feel free to add more)

**Comment by richgayle** [comment]
how about [recipe box]

**Comment by ybuchi** [comment]
FoodNoob
FoodLab
Recipeeps

**Comment by ybuchi** [comment]
Sous-Chef

**Comment by ybuchi** [comment]
UChef

**Comment by ybuchi** [comment]
ChefItUp

**Comment by ybuchi** [comment]
OuiChef

**Comment by swillaus** [comment]
FoodHub | CookingHub | UChef

**Comment by ybuchi** [comment]
**Yannik's Top 3 Choices**

1- SousChef (name already exists so will probably be SooChef.
2- FoodNoob
3- UChef

**Comment by richgayle** [comment]
uChef, 
FoodLab,
suChef

**Comment by Linag94** [comment]
foodnoob
uchef

**Comment by ybuchi** [comment]
**UChef 4**
FoodHub 1
CookingHub 1
Foodlab
SooChef / SuChef 2

**Comment by ybuchi** [comment]
THE APP NAME IS OFFICIALLY **UCHEF**. If we really hate it we can of course change it later. Closing the issue.
